# Generated by Django 6.0.2 on 2026-02-25 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serveHub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Paid')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update date')),
            ],
            options={
                'verbose_name': '2. Pay',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='reservation start')),
                ('end_time', models.DateTimeField(verbose_name='reservation end')),
                ('people_count', models.PositiveIntegerField(verbose_name='people count')),
                ('table_unit_price', models.PositiveIntegerField(verbose_name='table unit price')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('cancelled_by_user', 'Cancelled by user'), ('cancelled_by_manager', 'Cancelled by manager')], default='reserved', max_length=30, verbose_name='reservation status')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('attendance_status', models.CharField(choices=[('pending', 'Pending'), ('present', 'Present'), ('absent', 'Absent')], default='pending', max_length=20, verbose_name='attendance status')),
                ('attendance_marked_at', models.DateTimeField(blank=True, null=True, verbose_name='attendance marked at')),
                ('manager_decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='manager decision')),
                ('manager_decided_at', models.DateTimeField(blank=True, null=True, verbose_name='manager decided at')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update date')),
            ],
            options={
                'verbose_name': '3. Reservation',
                'verbose_name_plural': '3. Reservations',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('unit_price', models.PositiveIntegerField(verbose_name='unit price')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update date')),
            ],
            options={
                'verbose_name': '4. Reservation Item',
                'verbose_name_plural': '4. Reservation Items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='title')),
                ('total_amount', models.FloatField(verbose_name='total amount')),
                ('order_status', models.BooleanField(verbose_name='delivered')),
                ('cancellation', models.BooleanField(default=False, verbose_name='cancelled')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveHub.product', verbose_name='product')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveHub.table', verbose_name='Table')),
            ],
            options={
                'verbose_name': '1. Order',
            },
        ),
    ]
