# Generated by Django 5.2.8 on 2026-02-05 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serveHub', '0002_alter_category_id_alter_discount_id_alter_product_id_and_more'),
        ('user', '0002_alter_comment_id_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='title')),
                ('total_amount', models.FloatField(default=0.0, verbose_name='total amount')),
                ('order_status', models.BooleanField(default=False, verbose_name='status')),
                ('cancellation', models.BooleanField(default=False, verbose_name='cancellation')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveHub.product', verbose_name='product')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveHub.table', verbose_name='Table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='user')),
            ],
        ),
    ]
