# Generated by Django 6.0.2 on 2026-02-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
