# Generated by Django 6.0.1 on 2026-02-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_order_id_alter_pay_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '1. Order'},
        ),
        migrations.AlterModelOptions(
            name='pay',
            options={'verbose_name': '2. Pay'},
        ),
    ]
