# Generated by Django 6.0.2 on 2026-02-26 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_pay_order_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payment.reservation'),
        ),
    ]
