# Generated by Django 6.0.1 on 2026-02-08 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_order_options_alter_pay_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payment.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancellation',
            field=models.BooleanField(default=False, verbose_name='cancelled'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.BooleanField(verbose_name='delivered'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(verbose_name='total amount'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
    ]
