# Generated by Django 6.0.1 on 2026-02-19 11:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Enter discount amount', verbose_name='Discount Percent')),
                ('duration', models.DateTimeField(help_text='Discount validity duration', verbose_name='Valid Until')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(help_text='Enter table number', unique=True, verbose_name='Table Number')),
                ('table_type', models.CharField(choices=[('single', 'میز تک نفره'), ('couple', 'میز دو نفره'), ('family_3', 'میز سه نفره'), ('family_4', 'میز چهار نفره'), ('family_6', 'میز شش نفره'), ('family_8', 'میز هشت نفره - خانوادگی'), ('birthday', 'میز تولد (ویژه)'), ('vip', 'میز VIP')], default='family_4', max_length=20, verbose_name='Table Type')),
                ('capacity', models.IntegerField(help_text='Number of persons', verbose_name='Capacity')),
                ('duration', models.IntegerField(default=120, help_text='e.g., 120 minutes', verbose_name='Duration (minutes)')),
                ('price_per_person', models.IntegerField(help_text='Price per person in Toman', verbose_name='Price per Person (Toman)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tables/', verbose_name='Table Image')),
                ('description', models.TextField(blank=True, help_text='Description about the table (e.g., suitable for birthday)', null=True, verbose_name='Description')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available for Reservation')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='e.g., Espresso, Hot Drink, etc', max_length=30, verbose_name='Category Type')),
                ('description', models.TextField(blank=True, help_text='Category description', null=True, verbose_name='Description')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_discount', to='serveHub.discount', verbose_name='Category Discount')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter product name', max_length=50, verbose_name='Product Name')),
                ('image', models.ImageField(blank=True, help_text='Upload product image', null=True, upload_to='products_img/', verbose_name='Product Image')),
                ('product_rate', models.FloatField(default=0.0, help_text='Average rating of the product', verbose_name='Product Rating')),
                ('description', models.TextField(blank=True, help_text='e.g., espresso, steamed milk', null=True, verbose_name='Description / Ingredients')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('category', models.ForeignKey(help_text='Select product category', on_delete=django.db.models.deletion.CASCADE, to='serveHub.category', verbose_name='Category')),
                ('discount', models.ForeignKey(blank=True, help_text='Select discount if available', null=True, on_delete=django.db.models.deletion.SET_NULL, to='serveHub.discount', verbose_name='Discount')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='e.g., single, double, small, medium, large', max_length=50, verbose_name='Size / Type')),
                ('price', models.DecimalField(decimal_places=0, help_text='Price in Toman', max_digits=10, verbose_name='Price (Toman)')),
                ('quantity', models.IntegerField(default=1, help_text='Quantity available for this size', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Stock')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='serveHub.product', verbose_name='Main Product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'unique_together': {('product', 'size')},
            },
        ),
    ]
