# Generated by Django 6.0.2 on 2026-02-25 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeWorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True, verbose_name='Weekday')),
                ('opens_at', models.TimeField(verbose_name='Opens At')),
                ('closes_at', models.TimeField(verbose_name='Closes At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Cafe Working Hour',
                'verbose_name_plural': 'Cafe Working Hours',
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Enter discount amount', verbose_name='Discount Percent')),
                ('duration', models.DateTimeField(help_text='Discount validity duration', verbose_name='Valid Until')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='serveHub/media/tables', verbose_name='Table Image')),
                ('table_number', models.IntegerField(help_text='Enter table number', unique=True, verbose_name='Table Number')),
                ('table_type', models.CharField(choices=[('single', 'میز تک نفره'), ('couple', 'میز دو نفره'), ('family_3', 'میز سه نفره'), ('family_4', 'میز چهار نفره'), ('family_6', 'میز شش نفره'), ('family_8', 'میز هشت نفره - خانوادگی'), ('birthday', 'میز دیزاین تولد '), ('vip', 'میز VIP')], default='family_4', max_length=20, verbose_name='Table Type')),
                ('capacity', models.IntegerField(default=1, help_text='Number of persons', verbose_name='Capacity')),
                ('duration', models.IntegerField(default=120, help_text='e.g., 120 minutes', verbose_name='Duration (minutes)')),
                ('price_per_person', models.IntegerField(help_text='Price per person in Toman', verbose_name='Price per Person (Toman)')),
                ('description', models.TextField(blank=True, help_text='Description about the table (e.g., suitable for birthday)', null=True, verbose_name='Description')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available for Reservation')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='serveHub/media/categories', verbose_name='Image')),
                ('type', models.CharField(help_text='Hot drinks , cold drinks etc.', max_length=30, verbose_name='Category Name')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_discount', to='serveHub.discount', verbose_name='Category Discount')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('size1', models.CharField(help_text='Size according to the product', max_length=30)),
                ('price1', models.DecimalField(decimal_places=0, max_digits=10)),
                ('size2', models.CharField(blank=True, help_text='other Size according to the product', max_length=30, null=True)),
                ('price2', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('size3', models.CharField(blank=True, help_text='other Size according to the product', max_length=30, null=True)),
                ('price3', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serveHub.discount')),
            ],
            options={
                'verbose_name': 'Product Size',
                'verbose_name_plural': 'ProductSize',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload product image', null=True, upload_to='serveHub/media/products_img', verbose_name='Product Image')),
                ('name', models.CharField(help_text='Enter product name', max_length=50, verbose_name='Product Name')),
                ('product_rate', models.FloatField(default=0.0, help_text='Average rating of the product', verbose_name='Product Rating')),
                ('description', models.TextField(blank=True, help_text='Ingredients', null=True, verbose_name='Description / Ingredients')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('category', models.ForeignKey(help_text='Select product category', on_delete=django.db.models.deletion.CASCADE, to='serveHub.category', verbose_name='Category')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_discount', to='serveHub.discount', verbose_name='Product Discount')),
                ('size', models.ForeignKey(blank=True, help_text='Select product size', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='serveHub.productsize', verbose_name='Product Size')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
