# Generated by Django 6.0.1 on 2026-02-05 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Amount of Discount', verbose_name='Amount')),
                ('duration', models.DateTimeField(help_text='Duration of Discount', verbose_name='Duration')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='Create date of discount record', verbose_name='Create Date')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='Date of discount record Last Update', verbose_name='Last Update')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(help_text='Specific Number of Table', verbose_name='Table number')),
                ('capacity', models.IntegerField(help_text='Capacity of table', verbose_name='Capacity')),
                ('duration', models.TimeField(help_text='Duration of table usage', verbose_name='Duration')),
                ('price', models.IntegerField(help_text='Price of a Table', verbose_name='Price')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='Create date of a table', verbose_name='Create Date')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='last table record update', verbose_name='Last Update')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Type of Product', max_length=30, verbose_name='Type')),
                ('description', models.TextField(help_text='Description of Category', verbose_name='Description')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='Create date of Category', verbose_name='Create Date')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='Date of Category Last Update', verbose_name='Last Update')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_discount', to='serveHub.discount')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter product name', max_length=50, verbose_name='Product name')),
                ('price', models.DecimalField(decimal_places=2, help_text='enter price in toman', max_digits=10, verbose_name='Price')),
                ('product_rate', models.FloatField(default=0.0, help_text='average rating of the product', verbose_name='Product rating')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('category', models.ForeignKey(help_text='select product category', on_delete=django.db.models.deletion.CASCADE, to='serveHub.category', verbose_name='Category')),
                ('discount', models.ForeignKey(blank=True, help_text='select discount if available', null=True, on_delete=django.db.models.deletion.SET_NULL, to='serveHub.discount', verbose_name='Discount')),
            ],
        ),
    ]
