# Generated by Django 6.0.2 on 2026-02-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serveHub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_rate',
        ),
    ]
