# Generated by Django 6.0.2 on 2026-02-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serveHub', '0002_remove_product_product_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='discount',
        ),
    ]
