# Generated by Django 6.0.2 on 2026-02-26 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveHub', '0003_remove_category_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_discount', to='serveHub.discount', verbose_name='Category Discount'),
        ),
    ]
