# Generated by Django 6.0.1 on 2026-02-06 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveHub', '0005_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '3. Category'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': '4. Discount'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '2. Product'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': '1. Table'},
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default='', help_text='Quantity of product', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Quantity'),
        ),
    ]
