# Generated by Django 6.0.1 on 2026-02-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveHub', '0007_product_image_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='upload product image', null=True, upload_to='products_img/', verbose_name='Product Image'),
        ),
    ]
