# Generated by Django 6.0.2 on 2026-02-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveHub', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
