# Generated by Django 6.0.2 on 2026-02-18 11:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveHub', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'تخفیف', 'verbose_name_plural': 'تخفیف\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'میز', 'verbose_name_plural': 'میزها'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='مثال: اسپرسو، شیر با فوم کم', null=True, verbose_name='توضیحات / مواد تشکیل\u200cدهنده'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, help_text='نام محصول به انگلیسی', max_length=100, null=True, verbose_name='نام انگلیسی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات دسته\u200cبندی', null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='category',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_discount', to='serveHub.discount', verbose_name='تخفیف دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(help_text='مثال: اسپرسو، نوشیدنی گرم، etc', max_length=30, verbose_name='نوع دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.IntegerField(help_text='مقدار تخفیف را وارد کنید', verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='duration',
            field=models.DateTimeField(help_text='مدت اعتبار تخفیف', verbose_name='مدت اعتبار'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='دسته\u200cبندی محصول را انتخاب کنید', on_delete=django.db.models.deletion.CASCADE, to='serveHub.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='تخفیف را انتخاب کنید (در صورت وجود)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='serveHub.discount', verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='تصویر محصول را آپلود کنید', null=True, upload_to='products_img/', verbose_name='تصویر محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='نام محصول را وارد کنید', max_length=50, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_rate',
            field=models.FloatField(default=0.0, help_text='میانگین امتیازات محصول', verbose_name='امتیاز محصول'),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(help_text='ظرفیت میز (تعداد نفر)', verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='table',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='table',
            name='duration',
            field=models.TimeField(help_text='مدت زمان استفاده از میز', verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='table',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='table',
            name='price',
            field=models.IntegerField(help_text='قیمت میز به تومان', verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(help_text='شماره میز را وارد کنید', verbose_name='شماره میز'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='مثال: تک شات، جفت شات، کوچک، متوسط، بزرگ', max_length=50, verbose_name='اندازه / نوع')),
                ('price', models.DecimalField(decimal_places=0, help_text='قیمت به تومان', max_digits=10, verbose_name='قیمت (تومان)')),
                ('quantity', models.IntegerField(default=1, help_text='تعداد موجود برای این سایز', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='موجودی')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='serveHub.product', verbose_name='محصول اصلی')),
            ],
            options={
                'verbose_name': 'نوع محصول',
                'verbose_name_plural': 'انواع محصول',
                'unique_together': {('product', 'size')},
            },
        ),
    ]
