# Generated by Django 6.0.2 on 2026-02-18 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveHub', '0009_alter_category_options_alter_discount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Discount', 'verbose_name_plural': 'Discounts'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='table',
            name='price',
        ),
        migrations.AddField(
            model_name='table',
            name='description',
            field=models.TextField(blank=True, help_text='Description about the table (e.g., suitable for birthday)', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='table',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tables/', verbose_name='Table Image'),
        ),
        migrations.AddField(
            model_name='table',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Available for Reservation'),
        ),
        migrations.AddField(
            model_name='table',
            name='price_per_person',
            field=models.IntegerField(default=0, help_text='Price per person in Toman', verbose_name='Price per Person (Toman)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='table_type',
            field=models.CharField(choices=[('couple', 'میز دو نفره'), ('family_4', 'میز چهار نفره'), ('family_6', 'میز شش نفره'), ('family_8', 'میز هشت نفره - خانوادگی'), ('birthday', 'میز تولد (ویژه)'), ('vip', 'میز VIP')], default='family_4', max_length=20, verbose_name='Table Type'),
        ),
        migrations.AlterField(
            model_name='category',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Category description', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_discount', to='serveHub.discount', verbose_name='Category Discount'),
        ),
        migrations.AlterField(
            model_name='category',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Update'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(help_text='e.g., Espresso, Hot Drink, etc', max_length=30, verbose_name='Category Type'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.IntegerField(help_text='Enter discount amount', verbose_name='Discount Percent'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='duration',
            field=models.DateTimeField(help_text='Discount validity duration', verbose_name='Valid Until'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Update'),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(help_text='Number of persons', verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='table',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='table',
            name='duration',
            field=models.IntegerField(default=120, help_text='e.g., 120 minutes', verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Update'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(help_text='Enter table number', unique=True, verbose_name='Table Number'),
        ),
    ]
