# Generated by Django 6.0.2 on 2026-02-18 17:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveHub', '0010_alter_category_options_alter_discount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Select product category', on_delete=django.db.models.deletion.CASCADE, to='serveHub.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='e.g., espresso, steamed milk', null=True, verbose_name='Description / Ingredients'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='Select discount if available', null=True, on_delete=django.db.models.deletion.SET_NULL, to='serveHub.discount', verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload product image', null=True, upload_to='products_img/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Update'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Enter product name', max_length=50, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_rate',
            field=models.FloatField(default=0.0, help_text='Average rating of the product', verbose_name='Product Rating'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Update'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Price in Toman', max_digits=10, verbose_name='Price (Toman)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='serveHub.product', verbose_name='Main Product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Quantity available for this size', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(help_text='e.g., single, double, small, medium, large', max_length=50, verbose_name='Size / Type'),
        ),
    ]
