# Generated by Django 6.0.2 on 2026-02-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveHub', '0012_alter_table_table_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_type',
            field=models.CharField(choices=[('single', 'میز تک نفره'), ('couple', 'میز دو نفره'), ('family_3', 'میز سه نفره'), ('family_4', 'میز چهار نفره'), ('family_6', 'میز شش نفره'), ('family_8', 'میز هشت نفره - خانوادگی'), ('birthday', 'میز تولد (ویژه)'), ('vip', 'میز VIP')], default='family_4', max_length=20, verbose_name='Table Type'),
        ),
    ]
