# Generated by Django 6.0.1 on 2026-02-18 22:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serveHub', '0008_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=24, verbose_name='first name')),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=24, verbose_name='last name')),
                ('number', models.CharField(help_text='Enter your number', max_length=11, unique=True, verbose_name='number')),
                ('password', models.CharField(help_text='Enter your password', max_length=255, verbose_name='password')),
                ('user_rate', models.FloatField(default=0, verbose_name='user rate')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('user_presence', models.BooleanField(default=False, verbose_name='user presence')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
            ],
            options={
                'verbose_name': '1. user',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Enter your comment text', verbose_name='comment text')),
                ('com_rate', models.FloatField(default=0, help_text='Rate the product from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='comment rate')),
                ('is_delete', models.BooleanField(default=False, help_text='Mark if the comment is deleted', verbose_name='deleted status')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('product', models.ForeignKey(help_text='Select the product related to this comment', on_delete=django.db.models.deletion.CASCADE, to='serveHub.product', verbose_name='product')),
                ('user', models.ForeignKey(help_text='Select the user who wrote the comment', on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='user')),
            ],
            options={
                'verbose_name': '2. comment',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Enter your reply text', verbose_name='reply text')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.comment', verbose_name='comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='user')),
            ],
            options={
                'verbose_name': '3. Reply',
            },
        ),
        migrations.CreateModel(
            name='WorkingShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekdays', models.CharField(choices=[('S', 'Saturday'), ('SU', 'Sunday'), ('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday')], max_length=24, verbose_name='weekday')),
                ('opening_date', models.DateTimeField(help_text='Enter your opening date', verbose_name='opening date')),
                ('closed_date', models.DateTimeField(help_text='Enter your close date', verbose_name='closed date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='user')),
            ],
            options={
                'verbose_name': '4. Working Shift',
            },
        ),
    ]
