# Generated by Django 6.0.1 on 2026-02-05 15:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serveHub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=24, verbose_name='first name')),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=24, verbose_name='last name')),
                ('number', models.CharField(help_text='Enter your number', max_length=11, verbose_name='number')),
                ('password', models.CharField(help_text='Enter your password', max_length=24, verbose_name='password')),
                ('user_rate', models.FloatField(default=0, verbose_name='user rate')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('user_presence', models.BooleanField(default=False, verbose_name='user presence')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Enter your comment text', verbose_name='comment text')),
                ('com_rate', models.FloatField(default=0, help_text='Rate the product from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='comment rate')),
                ('delete', models.BooleanField(default=False, help_text='Mark if the comment is deleted', verbose_name='deleted status')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('product', models.ForeignKey(help_text='Select the product related to this comment', on_delete=django.db.models.deletion.CASCADE, to='serveHub.product', verbose_name='product')),
                ('user', models.ForeignKey(help_text='Select the user who wrote the comment', on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='user')),
            ],
        ),
    ]
