# Generated by Django 6.0.1 on 2026-02-05 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_comment_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '2.comment'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '1.user'},
        ),
    ]
