# Generated by Django 6.0.1 on 2026-02-06 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_comment_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '2. comment'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '1. user'},
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Enter your reply text', verbose_name='reply text')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.comment', verbose_name='comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekdays', models.CharField(choices=[('S', 'Saturday'), ('SU', 'Sunday'), ('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday')], max_length=24, verbose_name='weekday')),
                ('opening_date', models.DateField(help_text='Enter your opening date', verbose_name='opening date')),
                ('closed_date', models.DateField(help_text='Enter your close date', verbose_name='closed date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='user')),
            ],
        ),
    ]
