# Generated by Django 6.0.1 on 2026-02-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_comment_options_alter_user_options_reply_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': '3. Reply'},
        ),
        migrations.AlterModelOptions(
            name='workingshift',
            options={'verbose_name': '4. Working Shift'},
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='closed_date',
            field=models.DateTimeField(help_text='Enter your close date', verbose_name='closed date'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='opening_date',
            field=models.DateTimeField(help_text='Enter your opening date', verbose_name='opening date'),
        ),
    ]
