# Generated by Django 6.0.2 on 2026-02-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_reply_options_alter_workingshift_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='delete',
            new_name='is_delete',
        ),
    ]
